import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Panalobet Blogs',
    description: 'Generated by create next app',
}

export default function BlogLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return <>{children}</>
}
